language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "fav food is"$FAVORITE_FOOD

script:
  - docker --version # print the version for logging
  - docker build -t simple-node --build-arg FAVORITE_FOOD=${FAVORITE_FOOD} .
  - docker tag simple-node mamad0s3c/test-travis-project

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mamad0s3c/test-travis-project
